### ISSUE TITLE
Demo's and library isn't working - TypeError: Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by hollandben** [pc035860/angular-highlightjs#26]
The [demo page](http://pc035860.github.io/angular-highlightjs/example/) is no longer working. The error in the console reads:

`TypeError: Cannot read property 'configure' of undefined`

![image](https://cloud.githubusercontent.com/assets/1148714/3256094/684da078-f213-11e3-8395-9da22999043e.png)

**Comment by alexsomeoddpilot** [comment]
I'm having the same issue while using the library in my code.

The issue is coming from [this line](https://github.com/pc035860/angular-highlightjs/blob/master/angular-highlightjs.js#L44) which expects <var>hljs</var> to exist as a property on <var>window</var>, but the property is not set.

**Comment by alexsomeoddpilot** [comment]
I've determined the real cause is that I wasn't including the original highlightjs library.

Additionally, I'm using Browserify and expected this library to be pulled in automatically.

I'm working on a pull request which will solve for this.

**Comment by stickel** [comment]
This error happens when I use the npm modules for both `highlight.js` and `angular-highlightjs` along with webpack. Using `require('highlight.js');` to load the highlightjs library creates the `TypeError: Cannot read property 'configure' of undefined` error. When I add a `script` tag and load highlightjs from the CDN there are no errors and all works well. Is there a way to fix the error using `require` instead of calling highlightjs from a CDN?

**Comment by pc035860** [comment]
Will work on it this weekend. Thanks for the information!

**Comment by pc035860** [comment]
@stickel I just updated the module pattern to UMD. It's on `master` branch now. If it works for you, I'll make a release ASAP!

**Comment by stickel** [comment]
@pc035860 Close. As it is in `master` I was getting an error that the module `hljs` couldn't be found. Updating this conditional in `./build/angular-highlight.js`:
```js
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define(["angular", "hljs"], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory(require("angular"), require("highlight.js"));
  } else {
    root.returnExports = factory(root.angular, root.hljs);
  }
}(this, function (angular, hljs) {
```
to this:
```js
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // define(["angular", "hljs"], factory);
    module.exports = factory(require("angular"), require("highlight.js"));
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory(require("angular"), require("highlight.js"));
  } else {
    root.returnExports = factory(root.angular, root.hljs);
  }
}(this, function (angular, hljs) {
```
Everything started working with webpack. Not sure if/how it'll affect other build tools though.

I posted a few other files for the test app I was using in [this gist](https://gist.github.com/stickel/32ba52c44582ddd03100) as well to give you more context.

**Comment by pc035860** [comment]
It seems that webpack's `babel-loader` will try to resovle modules with every possible pattern (rather than just CommonJS), hence causing

```js
define(["angular", "hljs"], factory);
```

being looked up in your installed npm modules, where it can't find `hljs`-named module and caused the error.

I've updated the module name to sync with the CommonJS one. And It should be fine on `master` now.

**Comment by stickel** [comment]
@pc035860 Downloaded and tested the files from `master` and it's working great. :+1:

**Comment by pc035860** [comment]
Just released [v0.4.3](https://github.com/pc035860/angular-highlightjs/releases/tag/v0.4.3). Thanks!

**Comment by shekharkhedekar** [comment]
@pc035860 I still see this with v0.4.3 (and angular 1.3.17)

```TypeError: Cannot read property 'configure' of undefined at Object.ngModule.provider.$get (VM1394 angular-highlightjs.js:47)```

**Comment by shekharkhedekar** [comment]
Actually - I missed the removal of the highlight.js dependency. Looks like we need to include that separately (using bower for this)

**Comment by pc035860** [comment]
There's actually no official bower package of highlight.js now ([see here](https://github.com/isagalaev/highlight.js/issues/182#issuecomment-29251147)).
But there's an official npm package, you can just `npm install highlight.js --save` for it.

Since you're using webpack, this should work for you.

I'm still wondering whether to add `angular` and `highlight.js` dependencies to `package.json` or not...

**Comment by stickel** [comment]
@pc035860 Have you updated the `npm` package with the newest version? When I try installing `0.4.3` npm can't find that version.

**Comment by pc035860** [comment]
@stickel I forgot to publish the new version to npm... And I'm having some trouble publishing it at home. Will try to publish it tomorrow at work!

**Comment by pc035860** [comment]
v0.4.3 published on npm now. Sorry for the delay!
https://www.npmjs.com/package/angular-highlightjs

**Comment by stickel** [comment]
![yup](http://bukk.it/thischecksout.gif)

**Comment by nayzawoo** [comment]
'bower_components/angular-highlightjs/build/angular-highlightjs.min',
    'js/highlight.min',

to 

    'js/highlight.min',
    'bower_components/angular-highlightjs/build/angular-highlightjs.min',

**Comment by herrherrmann** [comment]
Last one did the trick for (loading `highlight.js` before `angular-highlightjs.js`) – super-important hint!

**Comment by TanyongTh** [comment]
@herrherrmann +1

**Comment by thekingofcity** [comment]
@ghost   Still helpful. ):
