### ISSUE TITLE
.js suffix for highlightjs dependency

### ISSUE THREAD

**Issue by divyakumarjain** [pc035860/angular-highlightjs#47]
I am trying to use angular-highlightjs with requirejs. because of dependency on "highlight.js" (notice th .js suffix) require tries to load highlightjs from application base path. Following extract from requirejs api

RequireJS also assumes by default that all dependencies are scripts, so it does not expect to see a trailing ".js" suffix on module IDs. RequireJS will automatically add it when translating the module ID to a path. With the paths config, you can set up locations of a group of scripts. All of these capabilities allow you to use smaller strings for scripts as compared to traditional <script> tags.
There may be times when you do want to reference a script directly and not conform to the "baseUrl + paths" rules for finding it. If a module ID has one of the following characteristics, the ID will not be passed through the "baseUrl + paths" configuration, and just be treated like a regular URL that is relative to the document:
1. Ends in ".js".
2. Starts with a "/".
3. Contains an URL protocol, like "http:" or "https:".

source: http://requirejs.org/docs/api.html

Also have a sample to play with.

https://jsfiddle.net/shg4wnfs/3/

**Comment by pc035860** [comment]
Hi @divyakumarjain 

I find that highlight.js is actually using different module names on `npm`(which is `highlight.js`) and as an AMD module(which is `hljs`).

I'll fix this ASAP. Thank you for your report.

**Comment by pc035860** [comment]
`npm` package name `highlight.js`
https://github.com/isagalaev/highlight.js/blob/master/package.json#L2

Built AMD module name `hljs`
https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L19

**Comment by pc035860** [comment]
Hi @divyakumarjain, should be fixed now. It's on `master` now.

**Comment by cAhmad** [comment]
Hi,

I have the same issue while using ES2015 modules with jspm. It try to load highlight.js which does not exist.

**Comment by pc035860** [comment]
@cAhmad I just release v0.5.0, which should have fixed the issue.

**Comment by cAhmad** [comment]
Hi, thanks for your new release.

But, it tries now to load `hljs.js` file which does not exist.
Don't know if it helps but I'm working with `jspm`, the module to load in my case is `highlightjs`

**Comment by pc035860** [comment]
@cAhmad I haven't use `jspm` before, I'll take a look this weekend.

Though it's very weird that it tries to load `hljs.js` in this case (seems to have different behavior than webpack), it won't work even if it reads the correct module name, which is `highlight.js`, since the CommonJS pattern module name used in the `angular-highlightjs`'s UMD pattern is based on `highlight.js`'s npm package name, not `highlightjs` (this one is the name on component).

I guess you still have to use `jspm` to install the `highlight.js` on `npm`, rather than [the one in `jspm`'s official registry](https://github.com/jspm/registry/blob/master/registry.json#L226).

So it's kind of difficult to support all kinds of module loaders these days...

**Comment by cAhmad** [comment]
Thanks for your reply.

I will use the npm version instead of the gihub one. If I got time I'll try some overrides.
