### ISSUE TITLE
passing values for include from $scope variables not working

### ISSUE THREAD

**Issue by balasivagnanam** [pc035860/angular-highlightjs#49]
Hi thanks for the awesome library, it is highly useful.

Currently I am facing an issue in rendering the code block.

In my case the code block that I want to render, is in separate file.
Also I want to make this configurable, this will be an input from JSON file. But when I use a scope variable as a paramater inside "include" it is not working.

```
<div hljs include="'file.html'">
  </div>
  <h5>not working</h5>
  <div hljs include="'{{fileName}}'">
</div>
```
check the plunker that I created for this.
http://plnkr.co/edit/4VoplzSggll1Qei6L2qO

**Comment by pc035860** [comment]
Hi @balasivagnanam ,

The `include` directive in `angular-highlightjs` as well as the built-in `ng-include` accept _angular expression_.

Simply put `fileName` in the `include` and it'll wok, since `fileName` it self is a valid angular expression whose eval result is `"file.html"` (_string_).

```html
<div hljs include="fileName"></div>
```

Here's the working plunk
http://plnkr.co/edit/BRY4MHZHM5BqLWKU0ibV

**Comment by balasivagnanam** [comment]
that works. thanks a lot. I am new to angular, sorry about that stupid question.
